// <auto-generated />
using FinalProject_HarryByrd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_HarryByrd.Migrations
{
    [DbContext(typeof(InstrumentContext))]
    [Migration("20231208222806_FinalProject")]
    partial class FinalProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_HarryByrd.Models.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = "B",
                            Name = "Brass"
                        },
                        new
                        {
                            CategoryId = "H",
                            Name = "Hybrid"
                        },
                        new
                        {
                            CategoryId = "K",
                            Name = "Keyboard"
                        },
                        new
                        {
                            CategoryId = "M",
                            Name = "Misc"
                        },
                        new
                        {
                            CategoryId = "N",
                            Name = "Psudeoinstrument"
                        },
                        new
                        {
                            CategoryId = "P",
                            Name = "Percussion"
                        },
                        new
                        {
                            CategoryId = "S",
                            Name = "String"
                        },
                        new
                        {
                            CategoryId = "W",
                            Name = "Woodwind"
                        });
                });

            modelBuilder.Entity("FinalProject_HarryByrd.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstrumentId"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstrumentId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            InstrumentId = 1,
                            CategoryId = "N",
                            Description = "Organ Pipe Mud Dauber nests look like pan flutes. Woah.",
                            Name = "Organ Pipe Mud Dauber's Nest",
                            Year = "45,000,000 BC"
                        },
                        new
                        {
                            InstrumentId = 2,
                            CategoryId = "H",
                            Description = "Product of string and brass copulation.",
                            Name = "Stroviol",
                            Year = "1899"
                        },
                        new
                        {
                            InstrumentId = 3,
                            CategoryId = "S",
                            Description = "Banjo, but big.",
                            Name = "Cello Banjo",
                            Year = "1889"
                        },
                        new
                        {
                            InstrumentId = 4,
                            CategoryId = "B",
                            Description = "Saxy figure, trumpet mechanics, two horns, one with built-in wah wah.",
                            Name = "Jazzophone",
                            Year = "1920"
                        },
                        new
                        {
                            InstrumentId = 5,
                            CategoryId = "B",
                            Description = "Trombone-like mouthpiece, woodwind-like tone holes, long curvy body. Snake? Snake?! SNAAAAAAAAAAKE!",
                            Name = "Serpent",
                            Year = "1590"
                        },
                        new
                        {
                            InstrumentId = 6,
                            CategoryId = "S",
                            Description = "Violin, but three-player.",
                            Name = "Triolin",
                            Year = "1991"
                        },
                        new
                        {
                            InstrumentId = 7,
                            CategoryId = "H",
                            Description = "Half euphonium, half lyre, half toilet.",
                            Name = "Loophonium",
                            Year = "1960"
                        },
                        new
                        {
                            InstrumentId = 8,
                            CategoryId = "M",
                            Description = "It's a theremin inside a badger.",
                            Name = "Badgermin",
                            Year = "2011"
                        },
                        new
                        {
                            InstrumentId = 9,
                            CategoryId = "W",
                            Description = "Flute, but REALLY big 4.",
                            Name = "Hyperbass Flute",
                            Year = "2001"
                        },
                        new
                        {
                            InstrumentId = 10,
                            CategoryId = "S",
                            Description = "42-stringed multi-necked guitar.",
                            Name = "Pikasso Guitar",
                            Year = "1984"
                        },
                        new
                        {
                            InstrumentId = 11,
                            CategoryId = "P",
                            Description = "Stiff bent wire, one end wooden ball, the other end hollow wooden box with loose metal \"teeth\". Smack ball to rattle.",
                            Name = "Vibraslap",
                            Year = "1967"
                        },
                        new
                        {
                            InstrumentId = 12,
                            CategoryId = "P",
                            Description = "Ancestor to the vibraslap, just a fuckin jawbone of a beast of burden or related species. Still smack to rattle.",
                            Name = "Quijada",
                            Year = "55,000,000 BC"
                        },
                        new
                        {
                            InstrumentId = 13,
                            CategoryId = "K",
                            Description = "A 3.5-acre electrically acutated lithophone in Luray Caverns, Virginia. Tap keys at the console, stalactites get tapped.",
                            Name = "The Great Stalacpipe Organ",
                            Year = "1956"
                        });
                });

            modelBuilder.Entity("FinalProject_HarryByrd.Models.Instrument", b =>
                {
                    b.HasOne("FinalProject_HarryByrd.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
